services:
  core:
    image: ghcr.io/system-pri/pri-core:latest
    env_file:
      - config.env
    ports:
      - "5432:5432"
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev
    restart: always

  ui:
    image: ghcr.io/system-pri/pri-ui-no-ssl:latest
    env_file:
      - config.env
    ports:
      - "80:80"
    restart: always